### ISSUE TITLE
So ye...

### ISSUE THREAD

**Issue by VanCock** [DKXLY/Tails-OH-NO#1]
So from what I have seen the coin puts you into survival in case you're in creative, bit weird, heads doesn't really do much, and tails always kick you out of the game, was kinda expecting something more like idk explosion, spawning stuff, or opposite, rewarding players, but no it's nothing or crash.

**Comment by ninem4re** [comment]
The coin actually puts you into adventure so you won't break any blocks, I am thinking about a reward for when you hit heads, and making the tails a bit more extreme, and heads kind of does something, and that's negating fall damage but that's pretty much useless bc you can do that with relogging. Thanks for your feedback and I hope this clears it up! :)
